!Config
app:
  monitor_refresh_time: 1
  monitor_observation: 60
  downloader_count:  3
  lock_timeout: 5
  config_dump: true
  sleep_time: 1
  log_count: 5
  log_count_extra: 7
  bucket_name: metal-price

redis:
  host: ?????
  port: 5030
  db: ?????

minio:
  endpoint: mimo
  access_key: ?????
  secret_key: ?????
  secure: false

data_source:
  api_key: ????


