!Config
app:
  monitor_refresh_time: 1
  monitor_observation: 60
  downloader_count:  3
  lock_timeout: 5
  config_dump: true
  sleep_time: 1
  cache_bucket: btc

redis:
  host: redis
  port: 5030
  db: 0

node:
  endpoint: ?????
  user: ?????
  password: ?????

minio:
  endpoint: mimo
  access_key: ?????
  secret_key: ?????
  secure: false


id_producer:
  max_queue_size: 300
  sleep_log: false

block_downloader:
  delay_start: 1.5
  max_queue_size: 300
  sleep_log: false