!Config
app:
  config_dump: true
  request_period_limit: 2000
  lock_timeout: 5
  monitor_refresh_time: 1.5
  log_count: 3
  log_count_extra: 5
  daily_range: 24
  hourly_range: 1
  symbol_rank_limit: 500


tasks:
  symbols: true
  exchanges: true
  assets: true
  ohlcv_daily: true
  ohlcv_hourly: true

redis:
  host: redis
  port: 5030
  db: ????

coinmarketcap:
  api_key: ?????

minio:
  endpoint: mimo
  access_key: ?????
  secret_key: ?????
  secure: false


