!Config
app:
  monitor_refresh_time: 1
  monitor_observation: 60
  downloader_count:  3
  inserter_count:  6
  lock_timeout: 5
  config_dump: true
  sleep_time: 1

mode:
  read_cache: true
  save_cache: true
  insert_db: true

redis:
  host: redis
  port: 5030
  db: 0

node:
  endpoint: ?????
  user: ?????
  password: ?????

minio:
  endpoint: mimo
  access_key: ?????
  secret_key: ?????
  secure: false

db:
  host: db
  drivername: postgresql+psycopg2
  username: ?????
  password: ?????
  port: 5480
  database: btc

id_producer:
  max_queue_size: 300
  sleep_log: false

block_downloader:
  delay_start: 1.5
  max_queue_size: 300
  sleep_log: true

block_inserter:
  sleep_log: false