!Config
app:
  monitor_refresh_time: 1
  monitor_observation: 60
  downloader_count:  8
  lock_timeout: 5
  config_dump: true
  cache_bucket: eth

redis:
  host: redis
  port: 5030
  db: 1

node:
  endpoint: ?????

minio:
  endpoint: mimo
  access_key: ?????
  secret_key: ?????
  secure: false

id_producer:
  max_queue_size: 500
  sleep_time: 2
  sleep_log: false

block_downloader:
  max_queue_size: 300
  sleep_time: 2
  sleep_log: false
  remove_elements:
    - transactions.receipt.blockHash
    - transactions.receipt.transactionHash
    #- logsBloom
    #- mixHash
    #- receiptsRoot
    #- sha3Uncles
    #- stateRoot
    #- transactionsRoot
    #- transactions.blockHash
    #- transactions.v
    #- transactions.r
    #- transactions.s
    #- transactions.chainId
    #- transactions.receipt.logsBloom
    #- transactions.receipt.root
    #- transactions.receipt.transactionIndex
    #- transactions.receipt.type
    #- uncles.logsBloom
    #- uncles.mixHash
    #- uncles.receiptsRoot
    #- uncles.sha3Uncles
    #- uncles.stateRoot
    #- uncles.transactionsRoot
