!Config
app:
  worker_count:  2
  lock_timeout: 5
  config_dump: true
  sleep_time: 1

monitor:
  refresh_time: 1
  observation: 60

id_producer:
  max_queue_size: 300
  sleep_log: false

worker:
  delay_start: 1.5
  sleep_log: false

redis:
  host: redis
  port: 5030
  db: 0

minio:
  endpoint: mimo
  access_key: ?????
  secret_key: ?????
  secure: false

run:
  - btc

tasks:
  btc:
    type: btc
    bucket_name: btc
    node:
      endpoint: ?????
      user: ?????
      password: ?????
