!Config
app:
  worker_count:  2
  lock_timeout: 5
  config_dump: true
  sleep_time: 1
  worker_delay_start: 1.5
  max_queue_size: 300

monitor:
  refresh_time: 1
  observation: 60

redis:
  host: redis
  port: 5030
  db: 0

minio:
  endpoint: mimo
  access_key: ?????
  secret_key: ?????
  secure: false

run:
  - btc
  - eth

tasks:
  btc:
    type: btc
    bucket_name: btc
    node:
      endpoint: ?????
      user: ?????
      password: ?????
  eth:
    type: eth
    bucket_name: eth
    node:
      endpoint: ?????
    remove_elements:
      - transactions.receipt.blockHash
      - transactions.receipt.transactionHash
      #- logsBloom
      #- mixHash
      #- receiptsRoot
      #- sha3Uncles
      #- stateRoot
      #- transactionsRoot
      #- transactions.blockHash
      #- transactions.v
      #- transactions.r
      #- transactions.s
      #- transactions.chainId
      #- transactions.receipt.logsBloom
      #- transactions.receipt.root
      #- transactions.receipt.transactionIndex
      #- transactions.receipt.type
      #- uncles.logsBloom
      #- uncles.mixHash
      #- uncles.receiptsRoot
      #- uncles.sha3Uncles
      #- uncles.stateRoot
      #- uncles.transactionsRoot