!Config
app:
  monitor_refresh_time: 1
  monitor_observation: 60
  worker_count:  3
  lock_timeout: 5
  config_dump: true
  no_data_sleep_time: 2
  log_count: 10
  log_count_extra: 15

redis:
  host: ?????
  port: 5030
  db: ?????

minio:
  endpoint: mimo
  access_key: ?????
  secret_key: ?????
  secure: false

run:
  - metal_price_api
  - farside_btc
  - farside_eth
  - coinmarketcap
  - biznes_radar

metal_price_api:
  enable: False
  bucket_name: metal-price
  api_key: ????

farside_btc:
  enable: False
  bucket_name: farside
  type: btc
  path: btc
  page: https://farside.co.uk/bitcoin-etf-flow-all-data/

farside_eth:
  enable: False
  bucket_name: farside
  type: eth
  path: eth
  page: https://farside.co.uk/ethereum-etf-flow-all-data/

coinmarketcap:
  enable: False
  bucket_name: coinmarketcap
  time_per_request_limit: 2000
  symbol_rank_limit: 500
  daily_range: 24
  hourly_range: 1
  refresh_threshold_days: 5
  tasks:
    symbols: True
    exchanges: True
    assets: True
    OHLCV_daily: True
    OHLCV_hourly: True
  api_key: ????

biznes_radar:
  enable: True
  bucket_name: biznes-radar
  time_per_request_limit: 2000
  tasks:
    symbols: False
    recommendations: False
    eod: True
    report: False